version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5-stretch
    working_directory: /go/src/github.com/evanj/stream
    steps:
      - checkout
      - run:
          name: run tests
          command: ./circleci.sh
